In [1]:
from xbbg import blp, Backend
import pandas as pd

In [2]:
tickers = ["AAPL US Equity", "6758 JP Equity"]
fields = ["name", "crncy", "px_last", "px_open", "volume"]

df_bdp = blp.bdp(tickers,fields,backend=Backend.PANDAS,format="long")
display(df_bdp.head())


df_bdp = (df_bdp.pivot(index="ticker", columns="field", values="value").reset_index().rename_axis(None, axis=1))
df_bdp = df_bdp[fields]
display(df_bdp)

           ticker    field       value
0  AAPL US Equity     name   APPLE INC
1  AAPL US Equity    crncy         USD
2  AAPL US Equity  px_last      297.84
3  AAPL US Equity  px_open      300.24
4  AAPL US Equity   volume  34482959.0

              name crncy px_last px_open      volume
0  SONY GROUP CORP   JPY  3676.0  3596.0   8249900.0
1        APPLE INC   USD  297.84  300.24  34482959.0

In [3]:
tickers = ["AAPL US Equity", "6758 JP Equity"]
fields = ["px_last","px_open","volume"]

df_bdh = blp.bdh(tickers,fields,"2026-05-01","2026-05-15",backend=Backend.PANDAS,format="long",Per="W")
display(df_bdh.head(4))


df_bdh = (df_bdh
    .assign(column_name=lambda x: x["ticker"].str.split().str[0] + "_" + x["field"])
    .pivot(index="date", columns="column_name", values="value")
    .reset_index()
    .rename_axis(None, axis=1)
)


tickers_short = [t.split()[0] for t in tickers]

ordered_cols = ["date"] + [
    f"{t}_{f}" for t in tickers_short for f in fields
]

df_bdh = df_bdh[ordered_cols]
display(df_bdh.head(3))

           ticker        date    field         value
0  AAPL US Equity  2026-05-01  px_last  2.801400e+02
1  AAPL US Equity  2026-05-01  px_open  2.660900e+02
2  AAPL US Equity  2026-05-01   volume  2.832972e+08
3  AAPL US Equity  2026-05-08  px_last  2.933200e+02

,date,AAPL_px_last,AAPL_px_open,AAPL_volume,6758_px_last,6758_px_open,6758_volume
0,2026-05-01,280.14,266.090,283297243.0,3127.0,3193.0,72714900.0
1,2026-05-08,293.32,279.655,252233246.0,3114.0,3124.0,97760000.0
2,2026-05-15,300.23,291.979,230867432.0,3576.0,3352.0,219785800.0

In [4]:
df = blp.bds(
        "AAPL US Equity",
        "DVD_HIST_ALL",
        backend=Backend.PANDAS,
    )

df.head()

,ticker,field,Declared Date,Ex-Date,Record Date,Payable Date,Dividend Amount,Dividend Frequency,Dividend Type
0,AAPL US Equity,DVD_HIST_ALL,2026-04-30,2026-05-11,2026-05-11,2026-05-14,0.27,Quarter,Regular Cash
1,AAPL US Equity,DVD_HIST_ALL,2026-01-29,2026-02-09,2026-02-09,2026-02-12,0.26,Quarter,Regular Cash
2,AAPL US Equity,DVD_HIST_ALL,2025-10-30,2025-11-10,2025-11-10,2025-11-13,0.26,Quarter,Regular Cash
3,AAPL US Equity,DVD_HIST_ALL,2025-07-31,2025-08-11,2025-08-11,2025-08-14,0.26,Quarter,Regular Cash
4,AAPL US Equity,DVD_HIST_ALL,2025-05-01,2025-05-12,2025-05-12,2025-05-15,0.26,Quarter,Regular Cash